# Site
title: "OLS"
description: >
  A mentoring & training program for Open Science ambassadors
logo: ''
email: team@we-are-ols.org
repository: open-life-science/open-life-science.github.io
twitter: openlifesci
gitter: open-life-sci/community
url: https://openlifesci.org/
announcement_list: https://groups.google.com/g/ols-news
youtube: https://www.youtube.com/channel/UCs12-ZgnDJOWIWN3Vo1XHXA/

markdown: kramdown

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata
